$ bvwbjplbgvbhsrlpgdmjqwftvncz
$ nppdvjthqldpwncqszvftbrmjlhg
$ nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg
$ zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw
⊜□¬⌕@\n.
Input ←

≡(+4⊢⊚≡(=4⧻⊝)◫4⊔)Input

$ mjqjpqmgbljsphdztnvjfqwrcgsmlb
$ bvwbjplbgvbhsrlpgdmjqwftvncz
$ nppdvjthqldpwncqszvftbrmjlhg
$ nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg
$ zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw
⊜□¬⌕@\n.
InputTwo ←

≡(+14⊢⊚≡(=14⧻⊝)◫14⊔)InputTwo

# Um, x_x
Generic ← ≡(|1 +∶⊢⊚≡(|1 =⧻⊝∶/⊔)≡⊢⊠(⊂∩□)⊙.◫,/⊔)∵⊂
Generic 4 Input
Generic 14 InputTwo
